version: '2'
services:
  zookeeper:
    image: aliirz/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build:
      context: .
      args:
        - RHEL_USERNAME=ali.raza.auditxprt
        - RHEL_PASSWORD=FN10/alias
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: rogue2.fzerolabs.com
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
